name: Tests

on:
  push:
    branches: ["*", "!master"]
  pull_request:
    branches: ["*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [12, 13, 14, 16]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Obtain NPM Cache directory
        id: node-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache NPM dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ steps.node-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - run: yarn install
      - run: yarn run lint
      - run: yarn run build
      - run: yarn test --ci
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -ct ${{ secrets.CODECOV_TOKEN }}
